=== TrellixVulnTeam/factory_349P/py/test/test_lists/test_list.schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "description": "reference: http://goto/cros-factory-test-list, ./TEST_LIST.md, ./JSON_TEST_LIST.md",
  "definitions": {
    "test_object": {
      "type": ["object", "string"],
      "properties": {
        "action_on_failure": {
          "type": "string",
          "enum": ["NEXT", "PARENT", "STOP"]
        },
        "args": {
          "type": "object"
        },
        "disable_abort": {
          "type": "boolean"
        },
        "disable_services": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "enable_services": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "exclusive_resources": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "has_ui": {
          "type": "boolean"
        },
        "id": {
          "type": "string"
        },
        "iterations": {
          "type": "number"
        },
        "label": {
          "type": ["string", "object"]
        },
        "locals": {
          "type": "object"
        },
        "never_fails": {
          "type": "boolean"
        },
        "parallel": {
          "type": "boolean"
        },
        "pytest_name": {
          "type": "string"
        },
        "retries": {
          "type": "number"
        },
        "run_if": {
          "type": "string"
        },
        "subtests": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/test_object"
          }
        },
        "teardown": {
          "type": "boolean"
        },
        "inherit": {
          "type": "string"
        },
        "child_action_on_failure": {
          "type": "string",
          "enum": ["NEXT", "PARENT", "STOP"]
        },
        "require_run": {
          "type": ["string", "array"],
          "items": {
            "type": "string"
          }
        },
        "__comment": {
          "description": "this field will be completely ignored by test list loader.",
          "type": "string"
        }
      },
      "additionalProperties": false
    },
    "test_options": {
      "__comment": "please see cros.factory.test.factory.Options",
      "type": "object"
    }
  },
  "type": "object",
  "properties": {
    "label": {
      "type": "string"
    },
    "inherit": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "options": {
      "$ref": "#/definitions/test_options"
    },
    "constants": {
      "type": "object"
    },
    "definitions": {
      "type": "object",
      "additionalProperties": {
        "$ref": "#/definitions/test_object"
      }
    },
    "tests": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/test_object"
      }
    },
    "override_args": {
      "__comment": "To override argument of a test in 'tests', maps the test path to a dictionary",
      "type": "object"
    },
    "__comment": {
      "description": "this field will be completely ignored by test list loader",
      "type": "string"
    }
  },
  "additionalProperties": false
}

=== TrellixVulnTeam/factory_349P/py/test/test_lists/manager_unittest/skipped_waived_tests.test_list.json
{
  "inherit": ["base.test_list"],
  "label": "Skip And Waive",
  "definitions": {
    "A": {
      "pytest_name": "nop"
    }
  },
  "options": {
    "skipped_tests": {
      "PROTO": [
        "A",
        "G.A"
      ]
    },
    "waived_tests": {
      "PROTO": [
        "A_2",
        "G.A_2"
      ]
    }
  },
  "tests": [
    "A",
    "A",
    {
      "id": "G",
      "subtests": [
        "A",
        "A"
      ]
    }
  ]
}

=== TrellixVulnTeam/factory_349P/py/test/test_lists/manager_unittest/locals.test_list.json
{
  "inherit": ["base.test_list"],
  "label": "Locals",

  "constants": {
    "phase": "EVT",
    "foo": "FOO"
  },

  "options": {
    "ui_locale": "zh-CN"
  },

  "definitions": {
    "NOP": {
      "pytest_name": "nop",
      "args": {
        "foo": "eval! locals.foo",
        "bar": "eval! locals.bar"
      }
    }
  },

  "tests": [
    {
      "id": "SMT",
      "locals": {
        "foo": "eval! constants.foo",
        "bar": "BAR"
      },
      "subtests": [
        "NOP",
        {
          "inherit": "NOP",
          "locals": {
            "bar": "BAZ"
          }
        },
        {
          "inherit": "NOP",
          "locals": {
            "foo": "eval! locals.bar",
            "bar": "BAZ"
          }
        }
      ]
    }
  ]
}

=== TrellixVulnTeam/factory_349P/py/test/test_lists/generic_main.test_list.json
{
  "inherit": [
    "generic_smt.test_list",
    "generic_fat.test_list",
    "generic_run_in.test_list",
    "generic_fft.test_list",
    "generic_grt.test_list"
  ],
  "label": "Main Test List for a Generic Chromebook.",
  "options": {
    "skipped_tests": {
      "device.factory.end_SMT": [
        "SMT"
      ],
      "device.factory.end_FAT": [
        "FAT"
      ],
      "device.factory.end_RUNIN": [
        "RunIn"
      ],
      "device.factory.end_FFT": [
        "FFT"
      ]
    },
    "ui_locale": "zh-CN"
  },
  "definitions": {
    "FATP": {
      "inherit": "FlattenGroup",
      "subtests": [
        "FAT",
        "RunIn",
        "FFT",
        "GRT"
      ]
    }
  },
  "tests": [
    "SMT",
    "FATP"
  ]
}

=== TrellixVulnTeam/factory_349P/py/test/test_lists/manager_unittest/a.test_list.json
{
  "inherit": [
    "base.test_list"
  ],
  "label": "A",
  "constants": {
    "component_list": [
      "cpu",
      "audio",
      "flash_chip"
    ],
    "enable_shopfloor": true,
    "phase": "EVT",
    "some_label": {
      "en-US": "us",
      "zh-CN": "cn"
    },
    "__comment_some_label": "real test list should use i18n! prefix instead.",
    "timestamp": 1,
    "__comment_timestamp": "this is used by testReloadConfig"
  },
  "options": {
    "disable_cros_shortcut_keys": true,
    "engineering_password_sha1": "dummy_password_sha1",
    "sync_event_log_period_secs": 0,
    "ui_locale": "zh-CN"
  },
  "definitions": {
    "LEDTest": {
      "pytest_name": "led",
      "args": {
        "colors": [
          "RED",
          "GREEN",
          "BLUE"
        ]
      }
    }
  },
  "tests": [
    {
      "id": "SMT",
      "subtests": [
        {
          "inherit": "LEDTest",
          "id": "FirstLEDTest"
        },
        {
          "inherit": "LEDTest",
          "id": "SecondLEDTest",
          "args": {
            "colors": [
              "RED",
              "GREEN"
            ]
          }
        },
        {
          "pytest_name": "verify_components",
          "args": {
            "component_list": "eval! constants.component_list",
            "skip_shopfloor": "eval! not constants.enable_shopfloor"
          }
        },
        {
          "inherit": "HaltStep",
          "id": "Halt",
          "require_run": "all"
        },
        "LEDTest",
        "LEDTest"
      ]
    }
  ]
}

=== TrellixVulnTeam/factory_349P/py/test/test_lists/manager_unittest/override_args.test_list.json
{
  "inherit": ["base.test_list"],
  "label": "Override Args",

  "constants": {
    "phase": "EVT",
    "enable_shopfloor": true,
    "component_list": ["cpu", "audio", "flash_chip"],
    "timestamp": 1,
    "__comment_timestamp": "this is used by testReloadConfig"
  },

  "options": {
    "engineering_password_sha1": "dummy_password_sha1",
    "ui_locale": "zh-CN",
    "sync_event_log_period_secs": 0,
    "disable_cros_shortcut_keys": true
  },

  "definitions": {
    "LEDTest": {
      "pytest_name": "led",
      "has_ui": true,
      "args": {
        "colors": ["RED", "GREEN", "BLUE"]
      }
    }
  },

  "tests": [
    {
      "id": "SMT",
      "subtests": [
        {
          "inherit": "LEDTest",
          "id": "FirstLEDTest"
        },
        {
          "inherit": "LEDTest",
          "id": "SecondLEDTest",
          "args": {
            "colors": ["RED", "GREEN"]
          }
        },
        "LEDTest",
        "LEDTest"
      ]
    }
  ],

  "override_args": {
    "SMT.FirstLEDTest": {
      "colors": ["RED"]
    },
    "SMT.SecondLEDTest": {
      "colors": ["BLUE"]
    },
    "SMT.LEDTest": {
      "colors": ["GREEN"]
    },
    "SMT.LEDTest-2": {
      "colors": ["WHITE"]
    }
  }
}
